### ISSUE TITLE
Layout is incorrect at Editing species page 

### ISSUE THREAD

**Issue by zhangwenx** [PecanProject/bety#307] opened 2015-06-03 17:46 UTC
Browser: Firefox
Go to Date -> Cultivars -> any link under Species ->click on Edit Record, the next page has a wrong layout

**Comment by dlebauer** [comment] 2015-06-04 02:06
Closing as duplicate of #280 (please reopen and update if this is incorrect)

**Closed by dlebauer** 2015-06-04 02:06 UTC
