### ISSUE TITLE
Layout is incorrect at Covariates showing and editing page 

### ISSUE THREAD

**Issue by zhangwenx** [PecanProject/bety#311] opened 2015-06-03 20:52 UTC
VM 1.4.2 , Firefox 
When click on show/edit action at any of Covariates from list, the layout on the next page is incorrect.

**Comment by dlebauer** [comment] 2015-06-04 02:10
Closing as duplicate of #280 (please reopen and update if this is incorrect)

**Closed by dlebauer** 2015-06-04 02:10 UTC
