### ISSUE TITLE
citations_sites: missing citations

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#163] opened 2015-01-07 22:04 UTC
```
select citation_id, count(*), array_agg(site_id) as site_id_list from citations_sites where citation_id not in (select id from citations) group by citation_id;
 citation_id | count |                     site_id_list                      
-------------+-------+-------------------------------------------------------
         474 |     1 | {781}
         484 |    13 | {796,899,900,901,902,903,904,905,906,907,908,909,910}
(2 rows)
```

**Comment by dlebauer** [comment] 2015-01-08 00:03
* I've fixed citation_id = 474 (it was a duplicate of 733)
* the sites listed that are associated with citation_id 484 in citations_sites are:

```
select id, state, sitename from sites where id in (select distinct site_id from citations_sites where citation_id not in (select id from citations))
id     sitename 
907	Wisconsin Young Red Pine (US-WI0)
901	Wisconsin Mature Hardwood (Us-WI3)
903	Wisconsin Intermediate Red Pine  (Us-WI2)
899	Wisconsin Clearcut Young Hardwood (US-WI8)
910	Wisconsin Wilson Flowage Sedge Marsh (US-WFL-fen)
900	Wisconsin Intermediate Hardwoods (US-WI1)
909	Wisconsin South Fork Spagnum Bog  (US-SFK-bog)
796	Bartlett Experimental Forest (US-Bar)
908	Wisconsin Young Jack Pine (US-WI9)
906	Wisconsin Clearcut Red Pine (US-WI7)
905	Wisconsin Mature Jack Pine (Us-WI5)
902	Wisconsin Pine Barrens (Us-WI6)
904	Wisconsin Mature red pine (Us-WI4)
```

@mdietze what is the appropriate citation for these?

**Comment by mdietze** [comment] 2015-01-08 00:16
Noormets et al 2007 Age-Dependent Changes in Ecosystem Carbon Fluxes in Managed Forests in Northern Wisconsin, USA. Ecosystems 10(2): 187-203, doi:http://dx.doi.org/10.1007/s10021-007-9018-y

**Comment by dlebauer** [comment] 2015-01-08 01:46
```sql
update citations_sites set citation_id = 781 where citation_id = 484
```

**Closed by dlebauer** 2015-01-08 01:46 UTC
