### ISSUE TITLE
Entering Dates 

### ISSUE THREAD

**Issue by echeng7** [PecanProject/bety#284] opened 2015-04-26 21:39 UTC
Entering the dates now requires for you to enter the year, month, and day or else it will not show up at all. For example, if only the year was given in a citation and LOC is year, I must enter 1995-01-01. If only 1995 was entered, no date will show up. I am unsure if this is intentional but I noticed it this week and thought it should be brought to your attention. @gsrohde

**Comment by gsrohde** [comment] 2015-04-27 21:26
@echeng7 Thanks very much for mentioning this!

Please be especially alert for things that may be broken or don't work the way you are used to and please bring them to our attention.  We recently did a major update to BETYdb, and it is likely there are other unexpected changes that we aren't yet aware of.

One other problem that I'd like to call your attention to--**_this is even more important than the problem with entering dates_**!  The problem is this: It used to be that after creating a new yield, you would be returned to the New Yield form with the form pre-filled with the values you just entered.  You could then change only the fields that were different for the _next_ yield you wanted to enter and press `Create` again and get another new yield inserted.  **_But there is a bug in the current version!_** After creating a yield, it still returns you to to a pre-filled version of the New Yield page as before.  But now when you change form values and click the `Create` button, **_instead of making a new yield, it will update the yield you just inserted!_**  Please be aware of this and either return to the index page after each time you create a new yield and then press the `New Yield` button before you make the next one, or wait until we fix this problem before you do more data entry.  **_This is probably a problem on the New Traits page as well!_**

We deployed the new changes on last Thursday afternoon.  There is only one yields row that was created after this.  If you think you created more than this, probably what happened is that you created one new yields row and then repeatedly updated it.  **_Please be aware of this and be prepared to re-enter data if necessary!_**

I am working on fixing these two problems now and hope to have the fixes in place by some time tomorrow.

**Comment by dlebauer** [comment] 2015-04-29 02:26
@gsrohde did you fix these errors yet?

**Comment by gsrohde** [comment] 2015-04-29 14:47
I plan to deploy the fixes today.

**Comment by gsrohde** [comment] 2015-04-30 16:29
@echeng7 

This, and the additional problems I mentioned in the above comment, are now fixed.

**Closed by gsrohde** 2015-04-30 16:29 UTC
