### ISSUE TITLE
Missing Miscanthus yield data?

### ISSUE THREAD

**Issue by samsrabin** [PecanProject/bety#493] opened 2017-03-21 13:56 UTC
I want to switch over to using the `traits` R package to access BETYdb, as opposed to using the VM as I had been doing. Unfortunately, that there appear to be fewer yields records accessible through `traits` than I was seeing on the VM. Some are even missing that appear via the betydb.org web interface.

Here are the `betydb_query` commands I have tried (both return identical numbers of records):

    yields <- betydb_query(table = 'yields')
    yields <- betydb_query(table = 'yields', api_version = 'beta', limit = 'none')

Here are the citations I expected to find in the yields table, but didn't:

    "49 NOT found: Clifton-Brown 2001 Performance of 15 Miscanthus Genotypes at Five Sites in Europe"
    "56 NOT found: Schwarz 1994 Studies of the growth and yield of miscanthus x giganteus in Germany"
    "57 NOT found: Himken 1997 Cultivation of Miscanthus under West European conditions: Seasonal changes in dry matter production, nutrient uptake and remobilization"
    "59 NOT found: Petrini 1998 Evaluation of Miscanthus Productivity in North-Central Italy"
    "61 NOT found: Kilpatrick 1996 Establishment, Growth and Dry Matter Yield of Miscanthus sacchariflorus over Two Years Under UK Conditions"
    "111 NOT found: Christian 2006 The recovery over several seasons of 15N-labelled fertilizer applied to Miscanthus x giganteus ranging from 1 to 3 years old"
    "112 NOT found: Bullard 1995 Shoot growth, radiation interception and dry matter production and partitioning during the establishment phase of Miscanthus sinensis 'Giganteus' grown at two densities in the UK"
    "116 NOT found: van der Werf 1993 Potential dry matter production of Miscanthus sinensis in The Netherlands"
    "128 NOT found: Jorgensen 1997 N2O emission from energy crop fields of Miscanthus \"giganteus\" and winter rye"
    "137 NOT found: Hotz 1996 Screening of different Miscanthus cultivars in respect of yield production and usability as a raw material for energy and industry"
    "142 NOT found: Clifton-Brown 2000 The modelled productivity of Miscanthus x giganteus (GREEF et DEU) in Ireland"
    "145 NOT found: Christian 2001 Agronomy of Miscanthus"
    "146 NOT found: Clifton-Brown 2001 Miscanthus productivity"
    "148 NOT found: Khale 2001 Cropping of Miscanthus in Central Europe: biomass production and influence on nutrients and soil organic matter"
    "149 NOT found: Lewandowski 2003 Delayed harvest of miscanthus--influences on biomass quantity and quality and environmental impacts of energy production"
    "150 NOT found: Acaroglu 2005 The cultivation and energy balance of Miscanthus x giganteus production in Turkey"
    "151 NOT found: Danalatos 1998 Influence of fertilisation and irrigation on the growth and biomass productivity of Miscanthus sinensis x giganteus under Greek conditions"
    "152 NOT found: Danalatos 1996 GROWTH AND BIOMASS PRODUCTIVITY OF MISCANTHUS SINENSIS \"GIGANTEUS\" UNDER OPTIMUM CULTURAL MANAGEMENT IN NORTH-EASTERN GREECE"
    "154 NOT found: Rohricht 1998 The suitability for cultivation, yield potential and ecological performance of energy crops grown on various soils in the German state of Saxony"
    "155 NOT found: Price 2004 Identifying the yield potential of Miscanthus x giganteus: an assessment of the spatial and temporal variability of M. x giganteus biomass productivity across England and Wales"
    "157 NOT found: Lewandowski 1998 Propagation method as an important factor in the growth and development of Miscanthus x giganteus"
    "158 NOT found: Lewandowski 1997 Combustion quality of biomass: practical relevance and experiments to modify the biomass quality of Miscanthus x giganteus"
    "659 NOT found: Masters 2014 EBI Farm Field Data"
    "691 NOT found: Ercoli 1999 Effect of irrigation and nitrogen fertilization on biomass yield and effciency of energy use in crop production of Miscanthus"
    "774 NOT found: Jorgensen 1996 Miscanthus yields in Denmark"

And here are the citations that WERE found, as expected:

    "50 found: Abbate 1996 Biomass crops for energy of possible introduction to Sicily"
    "58 found: Iglesias 1996 Miscanthus sinensis plantations in Galicia, north-west Spain: results and experience over the last three years"
    "110 found: Yazaki 2004 Carbon dynamics and budget in a Miscanthus sinensis grassland in Japan"
    "119 found: Christian 1997 The recovery of 15N-labelled fertilizer applied to Miscanthus giganteus"
    "156 found: Beale 1997 Seasonal dynamics of nutrient accumulation and partitioning in the perennial C4-grasses Miscanthus x giganteus and Spartina cynosuroides"
    "189 found: Clifton-Brown 2002 Screening Miscanthus genotypes in field trials to optimise biomass yield and quality in Southern Germany"
    "193 found: Dalianis 1994 Growth, biomass productivity and energy potential of giant reed (Arundo donax) and elephant grass (Miscanthus sinensis \"giganteus\")"
    "692 found: Arundale 2012 The higher productivity of the bioenergy feedstock Miscanthus x giganteus relative to Panicum virgatum is seen both into the long term and beyond Illinois"

**Comment by infotroph** [comment] 2017-03-22 09:12
I suspect this is because those records are [unchecked](https://github.com/ropensci/traits/blob/master/vignettes/betydb.Rmd#include_unchecked), but there's still an issue because adding `include_unchecked="true"` to the call ought to fix this but doesn't.

Simpler reprex: Noting that https://www.betydb.org/api/beta/yields/1277.json exists and has `"checked": 0`, it seems to me that https://www.betydb.org/api/beta/yields.json?id=1277 is correctly null, while https://www.betydb.org/api/beta/yields.json?id=1277&include_unchecked=true is wrongly null and ought to return 1 record. 

Right @gsrohde @dlebauer? Are there subtleties about `include_unchecked` working differently in `yields` than in the search view?

**Comment by infotroph** [comment] 2017-03-22 09:44
@samsrabin Here's a workaround in case you're in a hurry: A full citation record includes all the yields associated with it, so since you have citation ids already it's (at least kind) straightforward to join them all together:

```{r}
library(dplyr)
library(tidyr)
options(betydb_api_version="beta")

cited_yields <- (
    missing_cites
        # a dataframe with id = (49, 56, ..., 691, 774)
    %>% rename(citation_id = id)
    %>% group_by(citation_id)
    %>% do(yld = betydb_record(id = .$citation_id, table = "citations")$yields)
        # Get full record for each citation_id,
        # extract yields, store as a nested dataframe
    %>% unnest()
        # Works if all nested yields have same columns.
        # If any are null, filter them out before unnesting.
    %>% rename(yield_id = yield.id)
    %>% setNames(sub("^yield\\.", "", names(.)))
        # strip redundant prefixes off column names,
        # e.g. "yield.cultivar_id" -> "cultivar_id"
)
```

**Comment by samsrabin** [comment] 2017-03-22 10:45
Thanks @infotroph, that works works great. The only thing I had to change was to change `betydb_api_version` to `api_version` in the `options()` call. I have `traits` 0.2.0.9410; not sure if that's the reason for the difference.

**Comment by infotroph** [comment] 2017-03-22 11:45
@samsrabin Huh. I can't reproduce that with 0.2.0.9410, but if changing between `options(api_version="v0")` and `options(api_version="beta")` changes your output that's a bug in the traits package. It should only respond to five options and they all start with `betydb_`. If you can reproduce it, please submit a small self-contained example to the [traits repository](https://github.com/ropensci/traits).

**Comment by samsrabin** [comment] 2017-03-22 12:33
Ah, sorry, I had that wrong. It appears that doing `options(betydb_api_version = "beta")` has no effect, perhaps because `betydb_record()` is getting called within `do()`. What needs to happen is that I need to include `api_version = "beta"` in the `betydb_record()` call.

**Comment by infotroph** [comment] 2017-03-24 15:22
Probably related to this: Another example (from the [traits vignette](https://github.com/ropensci/traits/blob/master/vignettes/betydb.Rmd#include_unchecked)) where `include_unchecked` currently fails, but this time by NOT excluding unchecked records.

```
https://www.betydb.org/search.json?genus=Miscanthus&sitename=Durmersheim 
  # OK: 30 checked, 0 unchecked
https://www.betydb.org/search.json?genus=Miscanthus&sitename=Durmersheim&include_unchecked=true 
  # OK: 30 checked, 19 unchecked
https://www.betydb.org/api/beta/search.json?genus=Miscanthus&sitename=Durmersheim 
  # WRONG: 30 checked, 19 unchecked
https://www.betydb.org/api/beta/search.json?genus=Miscanthus&sitename=Durmersheim&include_unchecked=true 
  # OK: 30 checked, 19 unchecked
```

**Comment by gsrohde** [comment] 2017-03-28 16:53
@infotroph, @samsrabin: The `include_unchecked` parameter is not supported by the beta API.  (Unrecognized parameters are ignored.)  Compare https://pecan.gitbooks.io/betydb-data-access/content/original_api.html and https://pecan.gitbooks.io/betydb-data-access/content/API/beta_API.html; the latter makes no mention of the `include_unchecked` parameter.

In general, query options using the beta API are pretty closely tied to the column names of the table or view being queried.  So in place of `include_unchecked=false` (the default for this parameter in the "original" API), you can use `checked=1`.

**Comment by infotroph** [comment] 2017-03-28 17:53
@gsrohde Does that mean the beta API is supposed to include unchecked records by default? Right now it looks as if they're included in `search` but not in `traits` or `yields`, and as if filtering on `checked` doesn't change that:

```
https://www.betydb.org/api/beta/traits.json?limit=none
# 8504 checked, 0 unchecked
https://www.betydb.org/api/beta/traits.json?limit=none&checked=1
# 8504 checked, 0 unchecked
https://www.betydb.org/api/beta/traits.json?limit=none&checked=0
# 0 checked, 0 unchecked

https://www.betydb.org/api/beta/yields.json?limit=none
# 5566 checked, 0 unchecked
https://www.betydb.org/api/beta/yields.json?limit=none&checked=1
# 5566 checked, 0 unchecked
https://www.betydb.org/api/beta/yields.json?limit=none&checked=0
# 0 checked, 0 unchecked

https://www.betydb.org/api/beta/search.json?limit=none
# 21463 checked, 19531 unchecked
https://www.betydb.org/api/beta/search.json?limit=none&checked=1
# 21463 checked, 0 unchecked
https://www.betydb.org/api/beta/search.json?limit=none&checked=0
# 0 checked, 19531 unchecked
```

Is there any supported way of retrieving both checked and unchecked yields in the same query?

**Comment by gsrohde** [comment] 2017-03-30 17:54
@infotroph It took some doing to track down how this works, but here's what I've found:

For the traits and yields tables, only users with page access level "Administrator" (1) or "Manager" (2) can view unchecked traits or yields.  This is true not only for either API but also if one visits the Web pages for these tables.

This may or may not be a bug, but it may perhaps at least be considered a bug that this behavior is not documented on the API pages.  You may wish to bring this up with @dlebauer if you think this should work differently.

The other "hidden" filter is, of course, that users only see rows corresponding to their data access level.  (If you are using your own BETYdb instance and find this not to be true, be sure that you have the latest release.)

Regarding retrieving both checked and unchecked yields in the same query, this is actually the default for Adminstrator or Manager users. (As I just mentioned, unchecked rows are automatically filtered out of any query done by other users.)  Or rather, more precisely, the returned results will not be filtered at all by “checked” status unless the “checked” parameter is used.  But there actually is a third commonly-used “checked” status meaning “failed” (as in "failed QA" and symbolized by -1), and for the `/api/beta/traits` and `/api/beta/yields` endpoints, rows having this status will be returned as well.  (They are filtered out of the SQL view that `/search.json` and `/api/beta/search` connect to and they are filtered out in the “original” API—the `/traits.json` and `/yields.json` endpoints.)  To return _only_ the checked and unchecked but not the failed rows, one could use the beta API’s regular expression syntax.  For example, to get checked and unchecked rows but exclude failed rows, one could use the regular expression `^(0|1)$` which requires the rather obscure URL
```
https://www.betydb.org/api/beta/yields?checked=~%5E(0%7C1)%24
```
(Here I've used the URL escape codes for `^`, `|`, and `$`.)

**Comment by dlebauer** [comment] 2017-03-30 19:14
@gsrohde this is definitely a bug

* all users should have access to unchecked data
* failed data should never leave the database via the api

**Comment by dlebauer** [comment] 2017-03-30 20:02
@samsrabin sorry I've been away on vacation ... please try the queries again with the traits package and your API key. When you offered to help fix data I elevated your permissions so that you can access both the checked and unchecked data.

**Comment by dlebauer** [comment] 2017-03-30 20:03
@infotroph I'll update https://github.com/ropensci/traits/issues/52 with changes

**Comment by gsrohde** [comment] 2017-03-30 23:06
@dlebauer Re https://github.com/PecanProject/bety/issues/493#issuecomment-290515436: Just to clarify, all users _do_ have access to unchecked data, but only via the `search` resource (the traits and yields view).

Since, judging from the code, Patrick Mulrooney took some pains to implement hiding unchecked rows in the traits and yields tables from "ordinary" users, I can only conclude that either you two weren't on the same page as to how this should work or that you've changed your mind about how it should work in the intervening five years.

It isn't clear to me from your remarks if you want unchecked data "unhidden" only in the beta API or in both APIs or in both APIs and the Web page listings.  If you want to expedite this change, please make an issue for it explaining exactly what you changes want and what priority you want to give to this issue.  And then assign it to me.

**Comment by samsrabin** [comment] 2017-04-04 15:47
@dlebauer I can confirm that both queries work when I include my key as an argument.

**Closed** 2018-09-18 19:53 UTC
