### ISSUE TITLE
https://modex.bnl.gov/bety/variables/350 resetting on modex 

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/bety#594] opened 2018-08-29 11:31 UTC
Recently I asked @dlebauer to update the https://modex.bnl.gov/bety/variables/350 on BETYdb to include an additional underscore.  However after each sync with BETY the modex version resets to the old name:

BETYdb version
![screen shot 2018-08-29 at 7 26 22 am](https://user-images.githubusercontent.com/3067369/44784868-fd4fb380-ab5c-11e8-9f41-660aaebb8113.png)

modex.bnl.gov version
![screen shot 2018-08-29 at 7 28 09 am](https://user-images.githubusercontent.com/3067369/44784896-1a848200-ab5d-11e8-897e-d985b90c4845.png)

Our databases have synced many times since I have noticed this and each time that variable gets reset on modex.  I dont think I have a db login for another database (e.g. BU, UW) so i can't check that version

Any ideas?  I am actually actively using that variable so this is pretty frustrating to have to continually change since a space in the name/dir names actually seems to break pecan.  

Is it possible that all DBs are syncing with an old DB dump from BETYdb that isn't getting updated?

**Comment by mdietze** [comment] 2018-08-29 12:02
I can confirm that the second underscore is missing on psql-pecan.bu.edu/bety and that my sync is successfully matching schema with all other nodes. Not sure why it's not updating. @robkooper can you check that betydb.org is dumping correctly (and recently) and that the record is being written out

**Comment by mdietze** [comment] 2018-08-29 12:04
@robkooper Actually, just did a manual wget of the betydb.org tarball and it looks like it hasn't dumped successfully since July 20
```
-rw-r--r--@ 1 dietze  staff  4997969 Jul 20 11:25 bety.tar.gz
```

**Comment by robkooper** [comment] 2018-08-29 13:50
Thanks @mdietze. Not sure when or why but the code that dumps the database was commented out in my script. 

@serbinsh  I just forced a dump of the database can you check to see if this solves the issue and if so close it, or let me know if it is still wrong.

I will update the database on the VM before we release it so it is correct.

**Comment by robkooper** [comment] 2018-08-29 16:55
closing since sync now works.

**Closed by robkooper** 2018-08-29 16:55 UTC
Labels: bug, help wanted, question
